### PR TITLE
Feature 2 Autosnap Cleanup

### PR DESCRIPTION
**Pull request by kidynamit**
PR for #2

### CODE REVIEW

**Review by OdinsPlasmaRifle — APPROVED** [review]
This looks good. :shipit: 

Is the `oauth2client` package required for something now?

**Comment by kidynamit** [comment]
https://oauth2client.readthedocs.io/en/latest/

**Comment by kidynamit** [comment]
Oauth2client was explicitly being called in app.py (https://github.com/michailbrynard/autosnap-docker/blob/master/app.py#L11)

The docs above show that`google-api-python` have moved on to use `google-auth` and `oauthlib` combo. I have updated the branch to reflect this see 5c6cb78.

**Review by michailbrynard — APPROVED** [review]

**Comment by kidynamit** [comment]
closes #2

**Pull request merged**
